Update timer.gsc
* Added check for players number before ctw_max_wisp_enery_watch replaceFunc to ensure it does not accidentally run when more than 2p
* Corrected TranZit Maxis solo behaviour for Turbines
* Avoiding the following runtime error:
- in call to builtin function 'replacefunc'
    type undefined is not a function